config/routes.rb
SubscriptionService::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", registrations: "users/registrations", passwords: 'users/passwords', confirmations: 'users/confirmations' }
  
  resources :users
  resources :subscriptions do
    member do
      put 'cancel'
    end
  end
  
  get 'gift/:code', to: 'gifts#code'

  resources :credit_cards
  resources :bundles
  resources :gifts do
    member do
      get 'confirmation'
    end
    member do
      patch 'redeem', to: 'gifts#redeem'
    end
    member do
      get 'resend'
    end
  end

  get 'braintree' => 'braintree#challenge'
  post 'braintree' => 'braintree#webhook'
  
  get 'account' => 'users#account'
  
  get 'about' => 'home#about'
  get 'terms' => 'home#terms'
  get 'privacy' => 'home#privacy'
  get 'contact' => 'home#contact'
  get 'how' => 'home#how'
  
  root :to => "home#index"
  

  

end

app/models/user.rb
require 'mandrill'

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable,
         #:token_authenticatable, #:confirmable,
         :lockable, :timeoutable, :omniauthable, :omniauth_providers => [:facebook]

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :terms, :image
  attr_accessible :first_name, :last_name
  
  has_one :default_credit_card,  -> {where is_default: true}, :class_name => 'CreditCard'
  has_many :credit_cards
  has_many :credit_card_transactions
  has_many :subscriptions
  has_many :addresses, as: :addressable
  
  has_many :omniauths
  has_many :gift_recipients
  
  has_attached_file :image, 
    :styles => {
      :large => ["340x340>", :png],
      :medium => ["240x240>", :png],
      :small => ["140x140>", :png],
      :xsmall => ["40x40>", :png],
      :thumb => ["64x64#", :png]
    }, 
    :default_url => "/images/:style/missing.png"
  
  after_create :create_braintree_customer
  after_create :send_welcome_email
  
  def name
    if first_name.nil? && last_name.nil?
      "Anonymous User"
    else
      "#{first_name} #{last_name}"
    end
  end
  
  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = nil
    oauth = Omniauth.where(provider: auth.provider, uid: auth.uid).first
    unless oauth
      user = User.create(
        first_name: auth.extra.raw_info.first_name,
        last_name:  auth.extra.raw_info.last_name,
        email:      auth.info.email,
        password:   Devise.friendly_token[0,20]
      )
      user.omniauths << Omniauth.new({provider: auth.provider, uid: auth.uid, image: auth.info.image })
    else
      user = oauth.user
    end
    user
  end
  
  def self.find_for_twitter_oauth(auth, signed_in_resource=nil)
    user = nil
    oauth = Omniauth.where(provider: auth.provider, uid: auth.uid).first
    unless oauth
      user = User.create(
        first_name: auth.extra.raw_info.first_name,
        last_name:  auth.extra.raw_info.last_name,
        email:      auth.info.email,
        password:   Devise.friendly_token[0,20]
      )
      user.omniauths << Omniauth.new({provider: auth.provider, uid: auth.uid, image: auth.info.image })
    else
      user = oauth.user
    end
    user
  end
  
  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
        user.first_name = data["first_name"] if user.first_name.blank?
        user.last_name = data["last_name"] if user.last_name.blank?
        user.omniauth_image = data["image"] if user.omniauth_image.blank?
      end
    end
  end
  
  
  #protected
  def create_braintree_customer
    result = Braintree::Customer.create(
      :first_name => self.first_name,
      :last_name => self.last_name,
      :email => self.email
    )
    if result.success?
      self.update_attribute(:customer_id, result.customer.id) 
    else
      throw Exception.new "Error creating Braintree customer"
    end
  end
  #handle_asynchronously :create_braintree_customer
  
  def send_welcome_email
    mandrill = Mandrill::API.new 'wiogzUeHpLTaZz9vSORNxw'
    mandrill.messages.send_template 'welcome-email', nil, 
      {to: [name: self.name, email: self.email, type: 'to'], global_merge_vars: [{name: 'FIRSTNAME', content: self.first_name}]}
  end
  handle_asynchronously :send_welcome_email
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  def new
    self.resource = resource_class.new
  end

  # POST /resource/confirmation
  def create
    self.resource = resource_class.send_confirmation_instructions(resource_params)
    yield resource if block_given?

    if successfully_sent?(resource)
      respond_with({}, :location => after_resending_confirmation_instructions_path_for(resource_name))
    else
      flash[:alert] = 'Email address not found'
      respond_with(resource)

    end
  end

  # GET /resource/confirmation?confirmation_token=abcdef
  def show
    self.resource = resource_class.confirm_by_token(params[:confirmation_token])
    yield resource if block_given?

    if resource.errors.empty?
      set_flash_message(:notice, :confirmed) if is_flashing_format?
      respond_with_navigational(resource){ redirect_to after_confirmation_path_for(resource_name, resource) }
    else
      respond_with_navigational(resource.errors, :status => :unprocessable_entity){ render :new }
    end
  end

  protected

    # The path used after resending confirmation instructions.
    def after_resending_confirmation_instructions_path_for(resource_name)
      new_session_path(resource_name) if is_navigational_format?
    end

    # The path used after confirmation.
    def after_confirmation_path_for(resource_name, resource)
      if signed_in?
        account_path
      else
        new_session_path(resource_name)
      end
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
  
  def twitter
    @user = User.find_for_twitter_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Twitter") if is_navigational_format?
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  prepend_before_filter :require_no_authentication
  # Render the #edit only if coming from a reset password email link
  append_before_filter :assert_reset_token_passed, :only => :edit

  # GET /resource/password/new
  def new
    self.resource = resource_class.new
  end

  # POST /resource/password
  def create
    self.resource = resource_class.send_reset_password_instructions(resource_params)
    yield resource if block_given?

    if successfully_sent?(resource)
      respond_with({}, :location => after_sending_reset_password_instructions_path_for(resource_name))
    else
      flash[:alert] = "Email address not found"
      respond_with(resource)
    end
  end

  # GET /resource/password/edit?reset_password_token=abcdef
  def edit
    self.resource = resource_class.new
    resource.reset_password_token = params[:reset_password_token]
  end

  # PUT /resource/password
  def update
    self.resource = resource_class.reset_password_by_token(params[:user])

    yield resource if block_given?

    if resource.errors.empty?
      resource.unlock_access! if unlockable?(resource)
      flash_message = resource.active_for_authentication? ? :updated : :updated_not_active
      set_flash_message(:notice, flash_message) if is_flashing_format?
      sign_in(resource_name, resource)
      respond_with resource, :location => after_resetting_password_path_for(resource)
    else
      respond_with resource
    end
  end

  protected
    def after_resetting_password_path_for(resource)
      after_sign_in_path_for(resource)
    end

    # The path used after sending reset password instructions
    def after_sending_reset_password_instructions_path_for(resource_name)
      new_session_path(resource_name) if is_navigational_format?
    end

    # Check if a reset_password_token is provided in the request
    def assert_reset_token_passed
      if params[:reset_password_token].blank?
        set_flash_message(:alert, :no_token)
        redirect_to new_session_path(resource_name)
      end
    end

    # Check if proper Lockable module methods are present & unlock strategy
    # allows to unlock resource on password reset
    def unlockable?(resource)
      resource.respond_to?(:unlock_access!) &&
        resource.respond_to?(:unlock_strategy_enabled?) &&
        resource.unlock_strategy_enabled?(:email)
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  prepend_before_filter :require_no_authentication, :only => [ :new, :create, :cancel ]
  prepend_before_filter :authenticate_scope!, :only => [:edit, :update, :destroy]

  # GET /resource/sign_up
  def new
    build_resource({})
    respond_with self.resource
  end

  # POST /resource
  def create
    build_resource(sign_up_params)

    if resource.save
      yield resource if block_given?
      if resource.active_for_authentication?
        set_flash_message :notice, :signed_up if is_flashing_format?
        sign_up(resource_name, resource)
        respond_with resource, :location => after_sign_up_path_for(resource)
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_flashing_format?
        expire_data_after_sign_in!
        respond_with resource, :location => after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      respond_with resource
    end
  end

  # GET /resource/edit
  def edit
    render :edit
  end

  # PUT /resource
  # We need to use a copy of the resource because we don't want to change
  # the current user in place.
  def update
    self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)
    prev_unconfirmed_email = resource.unconfirmed_email if resource.respond_to?(:unconfirmed_email)

    if update_resource(resource, account_update_params)
      yield resource if block_given?
      if is_flashing_format?
        flash_key = update_needs_confirmation?(resource, prev_unconfirmed_email) ?
          :update_needs_confirmation : :updated
        set_flash_message :notice, flash_key
      end
      sign_in resource_name, resource, :bypass => true
      respond_with resource, :location => after_update_path_for(resource)
    else
      clean_up_passwords resource
      respond_with resource
    end
  end

  # DELETE /resource
  def destroy
    resource.destroy
    Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
    set_flash_message :notice, :destroyed if is_flashing_format?
    yield resource if block_given?
    respond_with_navigational(resource){ redirect_to after_sign_out_path_for(resource_name) }
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    expire_data_after_sign_in!
    redirect_to new_registration_path(resource_name)
  end

  protected

  def update_needs_confirmation?(resource, previous)
    resource.respond_to?(:pending_reconfirmation?) &&
      resource.pending_reconfirmation? &&
      previous != resource.unconfirmed_email
  end

  # By default we want to require a password checks on update.
  # You can overwrite this method in your own RegistrationsController.
  def update_resource(resource, params)
    resource.update_with_password(params)
  end

  # Build a devise resource passing in the session. Useful to move
  # temporary session data to the newly created user.
  def build_resource(hash=nil)
    self.resource = resource_class.new_with_session(hash || {}, session)
  end

  # Signs in a user on sign up. You can overwrite this method in your own
  # RegistrationsController.
  def sign_up(resource_name, resource)
    sign_in(resource_name, resource)
  end

  # The path used after sign up. You need to overwrite this method
  # in your own RegistrationsController.
  def after_sign_up_path_for(resource)
    #after_sign_in_path_for(resource)
    new_subscription_path
  end

  # The path used after sign up for inactive accounts. You need to overwrite
  # this method in your own RegistrationsController.
  def after_inactive_sign_up_path_for(resource)
    respond_to?(:root_path) ? root_path : "/"
  end

  # The default url to be used after updating a resource. You need to overwrite
  # this method in your own RegistrationsController.
  def after_update_path_for(resource)
    signed_in_root_path(resource)
  end

  # Authenticates the current scope and gets the current resource from the session.
  def authenticate_scope!
    send(:"authenticate_#{resource_name}!", :force => true)
    self.resource = send(:"current_#{resource_name}")
  end

  def sign_up_params
    devise_parameter_sanitizer.sanitize(:sign_up)
  end

  def account_update_params
    devise_parameter_sanitizer.sanitize(:account_update)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  
  def update
    if current_user.update(params[:user])
      # Sign in the user by passing validation in case his password changed
      sign_in current_user, :bypass => true
      flash[:notice] = "Your account was successfully updated"
      redirect_to account_path
    else
      render "edit"
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/account.html.haml
%ul.nav.nav-tabs{style: 'margin:10px 0px 20px;'}
  %li
    %a{href: '#account', 'data-toggle' => 'tab'} Account
  %li.active
    %a{href: '#subscription', 'data-toggle' => 'tab'} Subscription
  %li
    %a{href: '#gifts', 'data-toggle' => 'tab'} Gifts
  / %li
  /   %a{href: '#payments', 'data-toggle' => 'tab'} Payment

%div.tab-content
  %div#account.tab-pane
    %div.row
      %div.col-xs-12.col-sm-6.col-md-4.col-lg-4.col-sm-offset-0.col-md-offset-2
        = form_for(current_user, :url => user_path(current_user), :html => { role: 'form', :method => :put, :id => 'user-form' }) do |f|
          %div.panel.panel-default
            %div.panel-heading
              %h3.panel-title Personal Info
            %div.panel-body
              %div.row
                %div.form-group.col-xs-12
                  %label First Name
                  %input.form-control.required.first_name{type: 'text', id: 'user_first_name', name: 'user[first_name]', placeholder: 'First Name', value: current_user.first_name}

                %div.form-group.col-xs-12
                  %label Last Name
                  %input.form-control.required.last_name{type: 'text', id: 'user_last_name', name: 'user[last_name]', placeholder: 'Last Name', value: current_user.last_name}
                %div.form-group.col-xs-12
                  %label Email
                  %input.form-control.required.email{type: 'text', id: 'user_email', name: 'user[email]', placeholder: 'Email', value: current_user.email}

                %div.form-group.col-xs-12
                  %label{for: 'user_email'}
                  %button.btn.btn-primary.pull-right{type: 'submit', style: 'margin-top:0px;'} Update

      %div.col-xs-12.col-sm-6.col-md-4.col-lg-4
        = form_for(current_user, :url => user_path(current_user), :html => { role: 'form', :method => :put, :id => 'password-form' }) do |f|
          %div.panel.panel-default
            %div.panel-heading
              %h3.panel-title Change Password
            %div.panel-body
              %div.row
                %div.form-group.col-xs-12
                  %label Current Password
                  %input.form-control.required.password{type: 'password', id: 'user_old_password', placeholder: 'Current Password'}

                %div.form-group.col-xs-12
                  %label New Password
                  %input.form-control.required.new_password{type: 'password', id: 'user_password', name: 'user[password]', placeholder: 'New Password'}
                %div.form-group.col-xs-12
                  %label Confirm Password
                  %input.form-control.required.user_password_confirmation{type: 'password', id: 'user_password_confirmation', name: 'user[password_confirmation]', placeholder: 'Confirm New Password'}

                %div.form-group.col-xs-12
                  %button.btn.btn-primary.pull-right{type: 'submit', style: 'margin-top:0px;'} Update
  %div#subscription.active.tab-pane
    %div.row
      %div.col-xs-12.col-lg-10.col-lg-offset-1
        - current_user.subscriptions.each do |s|
          = render :partial => 'subscriptions/show', locals: {subscription: s}
  %div#gifts.tab-pane
    %div.row
    - current_user.gift_recipients.reverse.each do |gr|
      - unless gr.gift.nil?
        %div.col-xs-12.col-sm-6.col-md-3
          %div.panel.panel-default

            %div.panel-heading
              %div.row
                %div.col-xs-8
                  %h3.panel-title #{gr.first_name} #{gr.last_name}
                %div.col-xs-4.text-right
                  - if gr.gift.state == 'purchased'
                    %button.btn.btn-xs.btn-primary{type: 'button'}  Purchased
                  - else 
                    %button.btn.btn-xs.btn-success{type: 'button'}  Active
            %div.panel-body
              %img.img-responsive{src: 'http://img1.etsystatic.com/000/0/6059226/il_fullxfull.275770327.jpg', style: 'padding:0px 0px 10px;'}
              <p>You sent <b>#{gr.first_name} #{gr.last_name}</b> a #{gr.gift.plan.name} on #{gr.created_at.strftime("%B %-d, %Y")}</b></p>
              
              - unless gr.gift.orders.first.nil?
                - cct = gr.gift.orders.first.credit_card_transactions.first
                <p><b>$#{cct.amount}</b> was charged to your #{cct.credit_card}</p>
                - unless gr.gift.active?
                  %p.text-right
                    %a{href: "#{resend_gift_path(gr.gift)}"} resend notification
                

  / %div#payments.tab-pane
  /   %div.row
  /     %div.col-xs-12.col-sm-6.col-sm-offset-0.col-md-5.col-md-offset-1
        
  /       %div.panel.panel-default
  /         %div.panel-heading
  /           %h3.panel-title Credit Cards
  /         %div.panel-body
  /           = render :partial => 'credit_cards/index'
  /       = form_for(CreditCard.new, :url => credit_cards_path, :html => { :method => :post, :id => 'credit-card-form', :role => 'form' }) do |f|
  /         %div.panel.panel-default
  /           %div.panel-heading
  /             %h3.panel-title Add A Card
  /           %div.panel-body
  /             = render :partial => 'credit_cards/form'
  /     %div.col-xs-12.col-sm-6.col-sm-offset-0.col-md-5
        
  /       %div.panel.panel-default
  /         %div.panel-heading
  /           %h3.panel-title Transactions
  /         %div.panel-body
  /           = render :partial => 'credit_card_transactions/index'
      

%div.clearfix

= content_for :javascript do
  :plain
    $("#user-form").validate();
    $("#password-form").validate({
      rules: {
        "user[password_confirmation]": {
          equalTo: "#user_password"
        }
      }
    });

app/views/users/profile.html.haml
%div.container
  = form_for(current_user, :url => user_path(current_user), :html => { :method => :put, :id => 'user-form', :class => 'form-horizontal' }) do |f|
    %h2.form-signin-heading Update Your Profile
    %div.fileupload.fileupload-new{'data-provides' => 'fileupload'}
      %div.input-append
        %div.uneditable-input.span3
          %i.icon-file.fileupload-exists
          %span.fileupload-preview
        %span.btn.btn-file
          %span.fileupload-new Select file
          %span.fileupload-exists Change
        = f.file_field :image
      %a.btn.fileupload-exists{:href => '#', 'data-dismiss' => 'fileupload'} Remove
    = image_tag(current_user.image.url(:medium))
    = f.text_field :first_name, :placeholder => 'First Name'
    = f.text_field :last_name, :placeholder => 'Last Name'
    %button.btn.btn-lg.btn-primary.btn-block{:type => 'submit'} Save
 
          


= content_for :javascript do
  $("#user-form").validate();