config/routes.rb
SubscriptionService::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", registrations: "users/registrations", passwords: 'users/passwords', confirmations: 'users/confirmations' }
  
  resources :users
  resources :subscriptions do
    member do
      put 'cancel'
    end
  end
  
  get 'gift/:code', to: 'gifts#code'

  resources :credit_cards
  resources :bundles
  resources :gifts do
    member do
      get 'confirmation'
    end
    member do
      patch 'redeem', to: 'gifts#redeem'
    end
    member do
      get 'resend'
    end
  end

  get 'braintree' => 'braintree#challenge'
  post 'braintree' => 'braintree#webhook'
  
  get 'account' => 'users#account'
  
  get 'about' => 'home#about'
  get 'terms' => 'home#terms'
  get 'privacy' => 'home#privacy'
  get 'contact' => 'home#contact'
  get 'how' => 'home#how'
  
  root :to => "home#index"
  

  

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :user
  belongs_to :plan
  belongs_to :credit_card
  belongs_to :address
  
  attr_accessible :user, :plan, :token, :status, :credit_card, :address, :address_attributes, :address_id
  attr_accessible :billing_day_of_month, :first_billing_date, :billing_period_start_date, :billing_period_end_date, :paid_through_date
  attr_accessible :next_billing_date, :next_billing_period_amount, :failure_count

  has_many :orders
  has_many :shipments

  has_many :credit_card_transactions, through: :orders
  
  monetize :next_billing_period_amount_cents, :allow_nil => true

  accepts_nested_attributes_for :address
  
  # after_create :schedule_shipments
  state_machine :state, :initial => :active do
    event :cancel do
      transition :active => :canceled
    end
    
    before_transition on: :cancel, do: :do_cancel
  end

  protected
  def schedule_shipments
    (0..(self.plan.billing_cycle-1)).to_a.each do |i|
      self.shipments << Shipment.new(user: self.user, scheduled_at: Date.today.advance(months: i))
    end
  end

  def do_cancel
    result = Braintree::Subscription.cancel(self.token)
    # throw Exception.new unless result.success?
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :load_subscription, only: [:update, :cancel]
  
  def new
    @subscription = Subscription.new
  end
  
  def update
    @subscription.update_attributes! params[:subscription]

    respond_to do |format|
      format.js   { render :json => @subscription.as_json(include: :address), :status => 200 }
      format.html {
        flash[:notice] = 'Account successfully updated'
        redirect_to account_path
      }
    end
  end

  def cancel
    @subscription.cancel
    flash[:alert] = 'Your subscription was canceled.'
    redirect_to account_path
  end

  def create
    begin
      Subscription.transaction do
        # get the plan selected
        @plan = Plan.find_by_code params[:plan][:id]
      
        # get the shipping address, set default
        @address = Address.new params[:address]

        if params[:address_type] == 'existing-address'
          @address = current_user.addresses.find params[:subscription][:address_id]
        else
          @address = Address.new(params[:subscription][:address_attributes])
          current_user.addresses << @address
        end

        # handle credit card
        if params[:card_type] == 'existing-card'
          # get existing card, or
          @credit_card = current_user.credit_cards.find(params[:credit_card][:id])

        else
          # create new card on braintree
          result = Braintree::CreditCard.create(
            :customer_id => current_user.customer_id, 
            :number => params[:credit_card][:number], 
            :expiration_date => "#{params[:credit_card]['expires_at(2i)']}/#{params[:credit_card]['expires_at(1i)']}", 
            :cvv => params[:credit_card][:cvv]
          )
        
          # and save user card
          if result.success?
            @credit_card = CreditCard.new(
              :token => result.credit_card.token, 
              :card_type => result.credit_card.card_type, 
              :last4 => result.credit_card.last_4, 
              :expiration_month => result.credit_card.expiration_month, 
              :expiration_year => result.credit_card.expiration_year,
              :is_default => result.credit_card.default?
            ) 
            current_user.credit_cards << @credit_card
          else
            flash[:alert] = result.message
            throw Exception.new 
          end
        end

        # create an order
        
        @order = Order.create(user: current_user, address: @address)
        # create order line items
        @order.line_items << LineItem.new(sku: @plan.sku, sku_qty: 1, unit_price: @plan.sku.unit_price)
        # create invoice for order
        # @invoice = Invoice.create!(user: current_user, order: @order, subtotal: @plan.price, total: @plan.price, due_at: Time.now)
        @order.mark_invoiced
      

        # create a braintree subscription
        result = Braintree::Subscription.create(
          :payment_method_token => @credit_card.token,
          :plan_id => @plan.code
        )
      
        # if payment successful
        if result.success?
          # save credit card transaction details
          txn = result.subscription.transactions[0]
          @order.invoice.credit_card_transactions <<  CreditCardTransaction.new(
            :subject => @order,
            :user => current_user,
            :credit_card => @credit_card,
            :transaction_type => txn.type,
            :token => txn.id,
            :amount => txn.amount,
            :avs_error_response_code => txn.avs_error_response_code,
            :avs_postal_code_response_code => txn.avs_postal_code_response_code,
            :avs_street_address_response_code => txn.avs_street_address_response_code,
            :cvv_response_code => txn.cvv_response_code,
            :gateway_rejection_reason => txn.gateway_rejection_reason,
            :processor_authorization_code => txn.processor_authorization_code,
            :processor_response_code => txn.processor_response_code,
            :processor_response_text => txn.processor_response_text
          )
          
          # mark invoice as paid
          @order.invoice.mark_paid
          
          # save subscription details
          @subscription = Subscription.create(
            user: current_user,
            plan: @plan,
            address: @address,
            credit_card: @credit_card,
            token: result.subscription.id,
            billing_day_of_month: result.subscription.billing_day_of_month,
            billing_period_start_date: result.subscription.billing_period_start_date,
            billing_period_end_date: result.subscription.billing_period_end_date,
            failure_count: result.subscription.failure_count,
            first_billing_date: result.subscription.first_billing_date,
            next_billing_date: result.subscription.next_billing_date,
            next_billing_period_amount: result.subscription.next_billing_period_amount,
            paid_through_date: result.subscription.paid_through_date
          )
          # update order subscription
          @order.update_attribute(:subscription, @subscription)
          
          # schedule shipments
          (0..(@plan.billing_cycle-1)).to_a.each do |i|
            @order.shipments << Shipment.new(user: current_user, subscription: @subscription, address: @order.address, scheduled_at: Date.today.advance(months: i))
          end
          
        else

          flash[:alert] = result.message
          throw Exception.new result.message
        end
      end
      flash[:notice] = 'Subscription created successfully.  We hope you enjoy it!'
      redirect_to account_path
    rescue
      render 'new'
    end
  end

  protected
    def load_subscription
      @subscription = Subscription.find params[:id]
    end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_show.html.haml
%div.panel{class: (subscription.canceled? ? 'panel-warning' : 'panel-success') }
  %div.panel-heading
    %h1.panel-title
      %div.row
        %div.col-xs-8
          - if subscription.state == 'canceled'
            %button.btn.btn-xs.btn-warning{type: 'button'}  Canceled
          - else 
            %button.btn.btn-xs.btn-success{type: 'button'}  Active
          #{subscription.plan.name} Plan
        %div.col-xs-4.text-right
          %button.btn.btn-xs.btn-primary{type: 'button'} #{subscription.shipments.with_state(:pending).count} Deliveries Remaining
  %div.panel-body
    %div.row
      %div.col-xs-12{}
        
    %div.row
      %div.col-xs-12.col-sm-6

        %div.panel.panel-default
          / %div.panel-heading
          /   %h3.panel-title Last Shipment
          %div.panel-body#last-shipment
            = render partial: 'shipments/show', locals: {shipment: subscription.shipments.with_state(:shipped).order('shipped_at desc').first}
            %h4 Past Shipments
            %table.table.table-hover
              %tbody
                - subscription.shipments.with_state(:shipped).order('shipped_at desc').each do |shipment|
                  %tr
                    %td
                      = image_tag shipment.line_items.first.sku.images.first.url(:small)
                    %td #{shipment.line_items.first.sku.name}
                    %td #{shipment.shipped_at.strftime('%b %-d, %Y')}
      %div.col-xs-12.col-sm-6
        - if subscription.is_a?(Gift)  
          %div.panel.panel-default
            %div.panel-heading
              %h3.panel-title Gift From
            %div.panel-body
              %strong #{subscription.gift_recipient.user.name}

        %div.panel.panel-default
          %div.panel-heading
            %h3.panel-title Next Delivery On
          %div.panel-body
            %strong #{subscription.shipments.first.scheduled_at.advance(months: 1).strftime('%B %-d, %Y')}
        
        %div.panel.panel-default
          %div.panel-heading
            %div.row
              %div.col-xs-9
                %h3.panel-title Shipping To
              %div.row.col-xs-3.text-right
                %button.btn.btn-xs.btn-warning{id: "change-address-#{subscription.id}"} change
          = form_for subscription, html: {role: 'form', id: "update-address-#{subscription.id}"} do |f|
            %input{type: 'hidden', name: 'subscription[address_attributes][addressable_type]', value: 'User'}
            %input{type: 'hidden', name: 'subscription[address_attributes][addressable_id]', value: current_user.id }
            %div.panel-body
              %div.row
                %div.form-group.col-xs-12{id: "ship-to-#{subscription.id}"}
                  %strong #{subscription.address.first_name} #{subscription.address.last_name}<br/>
                  #{subscription.address.address1} #{subscription.address.address2}<br/>
                  #{subscription.address.city}, #{subscription.address.state} #{subscription.address.zip}
              
              %div{style: 'display:none;', class: "update-address-#{subscription.id}"}
                %div.row
                  %div.form-group.col-xs-12
                    %table.table.table-hover
                      %thead
                        %tr
                          %th{colspan: 2} Select an address ...
                      %tbody
                        - current_user.addresses.reverse.each do |address|
                          %tr
                            %td
                              %input{class: "shipping-address-#{subscription.id}", type: 'radio', name: 'subscription[address_id]', subscription_id: subscription.id, address_id: address.id, checked: (address.id == subscription.address.id)}
                            %td
                              #{address.to_s}
                %div.row
                  %div.form-group.col-xs-12
                    %table.table.table-hover
                      %thead
                        %tr
                          %th ... or add a new one
                      %tbody
                        %tr
                          %td
                            %div.row
                              %div.form-group.col-xs-12.col-md-6
                                %input.form-control.required.first_name{type: 'text', name: 'subscription[address_attributes][first_name]', id: 'address_first_name', placeholder: 'First Name', autofocus: true}
                              %div.form-group.col-xs-12.col-md-6
                                %input.form-control.last_name{type: 'text', name: 'subscription[address_attributes][last_name]', id: 'address_last_name', placeholder: 'Last Name'}
                              %div.form-group.col-xs-12.col-md-6
                                %input.form-control.required.address1{type: 'text', name: 'subscription[address_attributes][address1]', id: 'address_address1', placeholder: 'Address'}
                              %div.form-group.col-xs-12.col-md-6
                                %input.form-control.address2{type: 'text', name: 'subscription[address_attributes][address2]', id: 'address_address2', placeholder: 'Address (cont.)'}
                              
                              %div.form-group.col-xs-8.col-md-6
                                %input.form-control.required.city{type: 'text', name: 'subscription[address_attributes][city]', id: 'address_city', placeholder: 'City'}
                              %div.form-group.col-xs-4.col-md-2
                                %input.form-control.required.state{type: 'text', name: 'subscription[address_attributes][state]', id: 'address_state', placeholder: 'State'}
                              %div.form-group.col-xs-12.col-md-4
                                %input.form-control.required.zip{type: 'text', name: 'subscription[address_attributes][zip]', id: 'address_zip', placeholder: 'Zip Code'}
                            %div.row
                              %div.form-group.col-xs-12.text-right
                                %button.btn.btn-xs.btn-primary Add Address

        / %div.col-xs-12.col-sm-6
        / %div.panel.panel-default
        /   %div.panel-heading
        /     %h3.panel-title Last Delivery On
        /   %div.panel-body
        /     %strong #{subscription.shipments.first.scheduled_at.advance(months: 11).strftime('%B %-d, %Y')}

        - if subscription.active? && !subscription.is_a?(Gift)
          %div.panel.panel-default
            %div.panel-heading
              %div.row
                %div.col-xs-9
                  %h3.panel-title Subscription Renewal
                %div.row.col-xs-3.text-right
                  %button.btn.btn-xs.btn-warning{id: "change-payment-#{subscription.id}"} change
            %div.panel-body
              %div.row
                %div.col-xs-12
                  $#{money_without_cents subscription.next_billing_period_amount} will be charged to your
                  %span#payment-info #{subscription.credit_card.to_s} 
                  on #{subscription.next_billing_date.strftime('%B %-d, %Y')}
                
                %div{class: "update-payment-#{subscription.id}", style: 'display:none;'}
                  %div.row
                    %div.col-xs-12
                      %div.control-group
                        %div.credit-cards-alerts
                        %table.table.table-hover#credit-cards-table
                          %thead
                            %tr
                              %th{colspan: 5} Select a card ...
                          %tbody
                            - current_user.credit_cards.order('id desc').each do |credit_card|
                              %tr{:id => "credit_card_#{credit_card.id}", :style => 'cursor:pointer;'}
                                %td
                                  %div.control-group
                                    %div.controls.text-center
                                      - h = {:type => "radio", :class=> 'subscription-credit-card', :name => "subscription_credit_card", :id => credit_card.id, :value => credit_card.id}
                                      - h[:checked] = true if credit_card.is_default
                                      %input{ h }
                                %td
                                  = credit_card.card_type
                                %td
                                  = "x-#{credit_card.last4}"
                                %td
                                  = "#{credit_card.expiration_month}/#{credit_card.expiration_year}"
                                %td
                                  = link_to 'x', credit_card_path(credit_card), :method => :delete, :confirm => 'Are you sure?', :remote => true, :class => 'icon-remove'
                  %div.row
                    %div.form-group.col-xs-12
                      %table.table.table-hover
                        %thead
                          %tr
                            %th ... or add a new one
                        %tbody
                          %tr
                            %td
                              = form_for(CreditCard.new, :url => credit_cards_path, :html => { :method => :post, :id => 'credit-card-form', :role => 'form' }) do |f|
                                = render :partial => 'credit_cards/form'
        
        - unless subscription.is_a?(Gift)
          %div.panel.panel-default
            %div.panel-heading
              %h3.panel-title Payment History
            %div.panel-body
              = render :partial => 'credit_card_transactions/index', locals: {subscription: subscription}

    - if subscription.active? && !subscription.is_a?(Gift)
      %div.row
        %div.col-xs-12.text-right
          %button.btn.btn-xs.btn-danger{type: 'button', 'data-toggle' => 'modal', 'data-target' => '#cancel-modal'}  Cancel Subscription

%div.modal.fade#cancel-modal{role: 'dialog'}
  %div.modal-dialog
    %div.modal-content
      %div.modal-header
        %button.close{type: 'button', 'data-dismiss' => 'modal'} &times;
        %h4.modal-title Are you sure?
      %div.modal-body
        OMG, no!!!!!
      %div.modal-footer
        %button.btn.btn-default{type: 'button', 'data-dismiss' => 'modal'} Close
        = link_to 'Confirm', cancel_subscription_path(subscription), method: :put, class: 'btn btn-danger'


= content_for :javascript do
  $("#update-address-#{subscription.id}").validate();

= content_for :javascript do
  :plain
    
    $("#change-address-#{subscription.id}").click(function(){$(".update-address-#{subscription.id}").slideToggle();});
    $("#change-payment-#{subscription.id}").click(function(){$(".update-payment-#{subscription.id}").slideToggle();});

    $('.shipping-address-#{subscription.id}').change(function(){
      $.ajax({
        type: "PUT",
        dataType: 'json',
        url: "/subscriptions/" + $(this).attr('subscription_id'),
        data: { 'subscription[address_id]': $(this).attr('address_id') }
      }).done(function(data) {
        $("#ship-to-#{subscription.id}").html("<strong>" + data['address']['first_name'] + " " + data['address']['last_name'] + "</strong><br/>" + data['address']['address1'] + " " + data['address']['address2'] + "<br/>" + data['address']['city'] + ", " + data['address']['state'] + " " + data['address']['zip']);
        $('.update-address').slideToggle();
      });
    });

    $('.subscription-credit-card').change(function(){
      $.ajax({
        type: "PUT",
        url: "/credit_cards/" + this.id,
        data: { 'credit_card[is_default]': "true" },
        beforeSend: function() {$('#credit-cards-table').fadeTo('slow', 0.33);}
      }).done(function( data ) {
        $('#payment-info').html(data['card_type'] + " ending in " + data['last4']);
        $('#credit-cards-table').css({ opacity: 1.0 });
        $('.update-payment-<%=subscription.id%>').slideToggle();
      });
    });

app/views/subscriptions/new.html.haml
%style
  th { text-align:center;width:25%;}
  td { margin:auto;}
- @subscription ||= Subscription.new
- plan_id = params[:plan][:id] unless params[:plan].nil?
- plan_id = 'SEASON-TO-1-MONTH-SUB' if params[:plan].nil?
= form_for @subscription, url: {action: "create"}, html: {id: "new_subscription_form", role: 'form'} do |f|

  / %h1 Hi #{current_user.first_name}, let's get started ...
  
  %div.panel.panel-default
    %div.panel-heading
      %h3.panel-title Select a Plan
    %div.panel-body
      %table.table.plan-select
        %tr
          %td
            %div.plan-select
              %div.btn-group.btn-block
                %button.btn.btn-default.btn-block{style: 'height:66px;', type: 'button', value: 'SEASON-TO-1-MONTH-SUB', plan: 'Plan', duration: 1, price: 19}
                  %div.pull-right 
                    %b Monthly
                    %p $21/month
                  %img.img-responsive.img-thumbnail{src: asset_path('artisan.jpg'), style: 'width:35px;'}
        %tr  
          %td
            %div.plan-select
              %div.btn-group.btn-block
                %button.btn.btn-default.btn-block{style: 'height:66px', type: 'button', value: 'SEASON-TO-3-MONTH-SUB', plan: 'Plan', duration: 3, price: 54} 
                  %div.pull-right 
                    
                    %p 
                      $59
                      %br $19/month
                  %b 3 Months<br/>
                  %img.img-responsive.img-thumbnail{src: asset_path('flip.jpg'), style: 'width:35px;'}
                  %img.img-responsive.img-thumbnail{src: asset_path('flip.jpg'), style: 'width:35px;'}
                  
        %tr
          %td
            %div.plan-select
              %div.btn-group.btn-block
                %button.btn.btn-default.btn-block{style: 'height:50px', type: 'button', value: 'SEASON-TO-6-MONTH-SUB', plan: 'Plan', duration: 6, price: 102} 
                  %div.pull-right 
                    %b 6 Months
                    %p $115
                    %br $18/month
                  %img.img-responsive.img-thumbnail{src: asset_path('artisan.jpg'), style: 'width:35px;' }
                  %img.img-responsive.img-thumbnail{src: asset_path('artisan.jpg'), style: 'width:35px;' }
                  %img.img-responsive.img-thumbnail{src: asset_path('artisan.jpg'), style: 'width:35px;' }
        %tr        
          %td
            %div.plan-select
              %div.btn-group.btn-block
                %button.btn.btn-default.btn-block{style: 'height:50px;', type: 'button', value: 'SEASON-TO-12-MONTH-SUB', plan: 'Plan', duration: 12, price: 192} 
                  %div.pull-right 
                    %b 12 Months
                    %br
                    %p $215
                    %p $17/month
                  %img.img-responsive.img-thumbnail{src: asset_path('flip.jpg'), style: 'width:35px;'}
                  %img.img-responsive.img-thumbnail{src: asset_path('flip.jpg'), style: 'width:35px;'}
                  %img.img-responsive.img-thumbnail{src: asset_path('flip.jpg'), style: 'width:35px;'}
                  %img.img-responsive.img-thumbnail{src: asset_path('flip.jpg'), style: 'width:35px;'}

  %div.panel.panel-default
    %div.panel-heading
      %h1.panel-title Enter Your Shipping Address
    %div.panel-body
      = render partial: 'addresses/shipping'
  
  %div.col-xs-12.col-md-5
    %div.panel.panel-default
      %div.panel-heading
        %h3.panel-title Subscription Details
      %div.panel-body
        %table.table
          %tbody
            %tr
              %td Total # Shipments:
              %td
                %span#duration
            %tr
              %td First Shipment On:
              %td 
                %span#first
            %tr
              %td Last Shipment On:
              %td
                %span#last
            %tr
              %td Renews On:
              %td
                %span#renews
           
            

    %div.panel.panel-default
      %div.panel-heading
        %h3.panel-title Order Summary
      %div.panel-body
        %table{style: 'width:100%'}
          %tr
            %td
              %span#plan 1 Month Artisan Plan
            %td{style: 'text-align:right'}
              $
              %span#price 29.00
          %tr
            %td Tax (NY only)
            %td{style: 'text-align:right'}
              $
              %span#tax 2.32
          %tr{style: 'border-top:1px dotted gray'}
            %td
              %strong Total Due
            %td{style: 'text-align:right'}
              %strong
                $
                %span#total 31.32

    %div.panel.panel-default
      %div.panel-heading
        %h1.panel-title Payment Info
      %div.panel-body
        = render partial: 'credit_cards/payment'

        %button.btn.btn-lg.btn-success.btn-block{type: 'submit', id: 'purchase_button'} Buy Now! 
       
    %input{type: 'hidden', id: 'plan_id', name: 'plan[id]', value: 'SEASON-TO-1-MONTH-SUB'}
    
    %div.row
      %div.col-xs-12.col-md-8
                      
                
      
            
      %div.col-xs-12.col-md-4
        %div.row
          %div.col-xs-12
            
                      
            
                
        %div.row   
          %div.col-xs-12
          

  -# %h2 Enter payment info

  
  
  

= content_for :javascript do
  :plain
    var today = new Date();
    var last = new Date(today.getFullYear(),today.getMonth(),today.getDate());
    var renews = new Date(today.getFullYear(),today.getMonth()+1,today.getDate());
    
    $('#duration').html('1');
    $('#first').html($.datepicker.formatDate('M d, yy', today));
    $('#last').html($.datepicker.formatDate('M d, yy', last));
    $('#renews').html($.datepicker.formatDate('M d, yy', renews));
    
    $('div.plan-select button').click(
      function(){
        $('#price').html(($(this).attr('price')*1.0).toFixed(2));
        $('#tax').html(($(this).attr('price') * 0.08).toFixed(2));
        $('#total').html( ($(this).attr('price') * 0.08 + ($(this).attr('price')*1.0)).toFixed(2));
        $('#plan').html($(this).attr('duration') + ' Month ' + $(this).attr('plan'));
        $('#duration').html($(this).attr('duration'));
        
        last = new Date(today.getFullYear(),today.getMonth()+parseInt($(this).attr('duration'))-1,today.getDate());
        $('#last').html($.datepicker.formatDate('M d, yy', last));
        
        renews = new Date(today.getFullYear(),today.getMonth()+parseInt($(this).attr('duration')),today.getDate());
        $('#renews').html($.datepicker.formatDate('M d, yy', renews));
      }
    );
    $('#new_subscription_form').validate();
    $('div.plan-select div.btn-group.btn-block button').click(function(){
      $('div.plan-select div.btn-group.btn-block button').removeClass('active');
      $(this).addClass('active');
      $('#plan_id').val($(this).val());
      //event.preventDefault();
    });
    var num_buttons = $('div.plan-select div.btn-group.btn-block button').size();
    for(i = 0; i < num_buttons; i++) {
      var button = $('div.plan-select div.btn-group.btn-block button')[i];
      if($(button).val() == '#{plan_id}') {
        $(button).addClass('active');
        $('#price').html(($(button).attr('price')*1.0).toFixed(2));
        $('#total').html( (($(button).attr('price')*1.0)).toFixed(2));
        $('#plan').html($(button).attr('duration') + ' Month ' + $(button).attr('plan'));
        $('#duration').html($(button).attr('duration'));
        
        last = new Date(today.getFullYear(),today.getMonth()+parseInt($(button).attr('duration'))-1,today.getDate());
        $('#last').html($.datepicker.formatDate('M d, yy', last));
        
        renews = new Date(today.getFullYear(),today.getMonth()+parseInt($(button).attr('duration')),today.getDate());
        $('#renews').html($.datepicker.formatDate('M d, yy', renews));
        $('#plan_id').val($(button).val());
      }
    }