config/routes.rb
SubscriptionService::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", registrations: "users/registrations", passwords: 'users/passwords', confirmations: 'users/confirmations' }
  
  resources :users
  resources :subscriptions do
    member do
      put 'cancel'
    end
  end
  
  get 'gift/:code', to: 'gifts#code'

  resources :credit_cards
  resources :bundles
  resources :gifts do
    member do
      get 'confirmation'
    end
    member do
      patch 'redeem', to: 'gifts#redeem'
    end
    member do
      get 'resend'
    end
  end

  get 'braintree' => 'braintree#challenge'
  post 'braintree' => 'braintree#webhook'
  
  get 'account' => 'users#account'
  
  get 'about' => 'home#about'
  get 'terms' => 'home#terms'
  get 'privacy' => 'home#privacy'
  get 'contact' => 'home#contact'
  get 'how' => 'home#how'
  
  root :to => "home#index"
  

  

end

app/views/layouts/_alerts.html.erb
<div class="alerts">
<% if flash[:notice] %>
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= flash[:notice] %>
  </div>
  <% flash[:notice] = nil %>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-danger">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= flash[:alert] %>
  </div>
  <% flash[:alert] = nil %>
<% end %>
</div>

app/views/layouts/_facebook.html.erb
<% unless Rails.env.development? %>
<div id="fb-root"></div>
<% content_for :javascript do %>
  window.fbAsyncInit = function() {
    // init the FB JS SDK
    FB.init({
      appId      : '475835909192901',                        // App ID from the app dashboard
      status     : true,                                 // Check Facebook Login status
      xfbml      : true,                                  // Look for social plugins on the page
      cookie     : true
    });

    // Additional initialization code such as adding Event Listeners goes here
  };

  // Load the SDK asynchronously
  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) return;
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/all.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
<% end %>
<% end %>

app/views/layouts/_footer.html.haml
%div.footer
  %div.container
    %span.pull-left &copy; 2014 Season To
    %span.pull-right
      %a{href: '#'} Terms of Service
      &middot;
      %a{href: '#'} Privacy Policy
      &middot;
      %a{href: '#'} Contact Us

app/views/layouts/_javascript.html.erb
<script type="text/javascript">//<![CDATA[
$(document).ready(function(){

<%= yield :javascript %>

(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-47687013-1', 'season.to');
ga('send', 'pageview');

});
//]]></script>

app/views/layouts/_nav.html.haml
%nav.navbar.navbar-default.navbar-fixed-top{role: 'navigation'}
  %div.container
    %div.navbar-header
      %button.navbar-toggle{type: 'button', 'data-toggle' => 'collapse', 'data-target' => '.navbar-collapse'}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{href: '/'} Season To
    %div.navbar-collapse.collapse
      %ul.nav.navbar-nav.scroll
        - unless user_signed_in?
          %li
            %a{href: '#mission'} Our Mission
          %li
            %a{href: '#how'} How it Works

          %li
            %a{href: '#signup'} Sign Up
          %li
            %a{href: '#gift'} Buy a Gift
        - else
          %li
            %a{href: "#{new_gift_path}"} Buy a Gift
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li #{link_to 'Account', account_path}
          %li #{link_to 'Logout', destroy_user_session_path, method: :delete }
        - else
          %li #{link_to 'Login', new_user_session_path}
        
- unless user_signed_in?
  - content_for :javascript do
    $('ul.nav.scroll li a').on('click', function(event) {
    $("html, body").animate({ scrollTop: $(event.target.getAttribute('href')).offset().top - 30 }, 300); return false;
    });

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Season To</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="description" content="Season To - A gourmet salt and pepper subscription service">
  
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href='<%= asset_path("ico/apple-touch-icon-144-precomposed.png")%>'>
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href='<%= asset_path("ico/apple-touch-icon-114-precomposed.png")%>'>
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href='<%= asset_path("ico/apple-touch-icon-72-precomposed.png")%>'>
  <link rel="apple-touch-icon-precomposed" href='<%= asset_path("ico/apple-touch-icon-57-precomposed.png") %>'>
  <!-- <link rel="shortcut icon" href='<%= asset_path("ico/favicon.png")%>'> -->
  
  <!-- GOOGLE WEB FONTS -->
  <link href='http://fonts.googleapis.com/css?family=Sanchez' rel='stylesheet' type='text/css'>
  
 <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>

  <!-- Latest compiled and minified CSS -->
  <!-- <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css"> -->

  <!-- Optional theme -->
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">



  
  <%= csrf_meta_tags %>
</head>

<body id="home" data-spy="scroll" data-target=".navbar-collapse" data-offset="40">
  <%= render partial: 'layouts/nav' %>
  <%= render partial: 'layouts/alerts' %>

  <% unless params[:controller] == 'home' && params[:action] == 'index'%> <div class="container"><% end %>
  <%= yield %>
  <% unless params[:controller] == 'home' && params[:action] == 'index'%> </div><% end %>

  <%= render partial: 'layouts/footer' %>

<%= render :partial => 'layouts/facebook' %>
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
<!-- <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script> -->

<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
<%= render :partial => 'layouts/javascript' %>
</body>
</html>